version: '3.1'
services:
  stats-server:
    build: stats/server
    image: java-explore-with-me-stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    entrypoint:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/statistics
      - SPRING_DATASOURCE_USERNAME=statistics
      - SPRING_DATASOURCE_PASSWORD=statistics

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=statistics
      - POSTGRES_USER=statistics
      - POSTGRES_DB=statistics

  #  ewm-service:
  #    ports:
  #      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine